// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"github.com/zgsm-ai/codebase-indexer/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/comparison",
				Handler: compareCodebaseHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/files/content",
				Handler: getFileContentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/files/upload",
				Handler: uploadFilesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/codebase-indexer"),
	)


	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/relations",
				Handler: relationHandler(serverCtx),
			},
		},
		rest.WithPrefix("/codebase-indexer"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/semantics",
				Handler: semanticSearchHandler(serverCtx),
			},
		},
		rest.WithPrefix("/codebase-indexer"),
	)
}
