// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"github.com/zgsm-ai/codebase-indexer/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/codebases/directory",
				Handler: codebaseTreeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/files/content",
				Handler: getFileContentHandler(serverCtx),
			},
		},
		rest.WithPrefix("/codebase-indexer"),
	)


	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/search/relation",
				Handler: relationHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/search/definition",
				Handler: definitionQueryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/files/structure",
				Handler: definitionParseHandler(serverCtx),
			},
		},
		rest.WithPrefix("/codebase-indexer"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/search/semantic",
				Handler: semanticSearchHandler(serverCtx),
			},
		},
		rest.WithPrefix("/codebase-indexer"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/index/summary",
				Handler: summaryHandler(serverCtx),
			},
		},
		rest.WithPrefix("/codebase-indexer"),
	)
}
