apiVersion: v1
kind: ConfigMap
metadata:
  name: codebase-querier-config
  namespace: shenma
data:
  conf.yaml: |
    Name: codebase-querier
    Host: 0.0.0.0
    Port: 8888
    Timeout: 120000 #ms
    MaxConns: 500
    MaxBytes: 104857600 # 100MB
    DevServer:
      Enabled: true
    Verbose: false
    Mode: test # dev,test,rt,pre, pro
      
    Auth:
      UserInfoHeader: "x-userinfo"
    
    Log:
      Mode: console # console,file,volume
      ServiceName: "codebase-querier"
      Encoding: plain # json,plain
      Path: "/app/logs"
      Level: info # debug,info,error,severe
      KeepDays: 7
      MaxSize: 100 # MB per file, take affect when Rotation is size.
      Rotation: daily # split by day or size
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codebase-querier
  namespace: shenma
  labels:
    app: codebase-querier
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codebase-querier
  template:
    metadata:
      labels:
        app: codebase-querier
    spec:
      containers:
      - name: codebase-querier
        image: zgsm/codebase-querier:2025.06.26.5
        imagePullPolicy: IfNotPresent
        command:
          - /app/server
          - -f
          - /app/conf/conf.yaml
        ports:
        - containerPort: 8888
          name: http
        - containerPort: 6060
          name: metrics
        env:
          - name: TZ
            value: Asia/Shanghai
        livenessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: "4"
            memory: 8Gi
          limits:
            cpu: "8"
            memory: 16Gi
        volumeMounts:
        - name: app-conf
          mountPath: /app/conf
      volumes:
        - name: app-conf
          configMap:
            name: codebase-querier-config
---
apiVersion: v1
kind: Service
metadata:
  name: codebase-querier-svc
  namespace: shenma
spec:
  ports:
  - port: 8888
    targetPort: 8888
    name: http
  - port: 6470
    targetPort: 6060
    name: metrics
  selector:
    app: codebase-querier
