// go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
// protoc --go_out=. internal/store/codegraph/definition.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: internal/store/codegraph/definition.proto

package codegraphpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 代码文件结构
type CodeDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`               // 文件相对路径
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`       // 编程语言
	Definitions   []*Definition          `protobuf:"bytes,3,rep,name=definitions,proto3" json:"definitions,omitempty"` // 定义列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeDefinition) Reset() {
	*x = CodeDefinition{}
	mi := &file_internal_store_codegraph_definition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeDefinition) ProtoMessage() {}

func (x *CodeDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_internal_store_codegraph_definition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeDefinition.ProtoReflect.Descriptor instead.
func (*CodeDefinition) Descriptor() ([]byte, []int) {
	return file_internal_store_codegraph_definition_proto_rawDescGZIP(), []int{0}
}

func (x *CodeDefinition) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CodeDefinition) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CodeDefinition) GetDefinitions() []*Definition {
	if x != nil {
		return x.Definitions
	}
	return nil
}

// 代码定义
type Definition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`           // 定义类型
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`           // 名称
	Range         []int32                `protobuf:"varint,3,rep,packed,name=range,proto3" json:"range,omitempty"` // [startLine, startColumn, endLine, endColumn] (0-based)
	Signature     string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"` // 签名
	Content       []byte                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Definition) Reset() {
	*x = Definition{}
	mi := &file_internal_store_codegraph_definition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Definition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Definition) ProtoMessage() {}

func (x *Definition) ProtoReflect() protoreflect.Message {
	mi := &file_internal_store_codegraph_definition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Definition.ProtoReflect.Descriptor instead.
func (*Definition) Descriptor() ([]byte, []int) {
	return file_internal_store_codegraph_definition_proto_rawDescGZIP(), []int{1}
}

func (x *Definition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Definition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Definition) GetRange() []int32 {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *Definition) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Definition) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_internal_store_codegraph_definition_proto protoreflect.FileDescriptor

const file_internal_store_codegraph_definition_proto_rawDesc = "" +
	"\n" +
	")internal/store/codegraph/definition.proto\x12\vcodegraphpb\"{\n" +
	"\x0eCodeDefinition\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x129\n" +
	"\vdefinitions\x18\x03 \x03(\v2\x17.codegraphpb.DefinitionR\vdefinitions\"\x82\x01\n" +
	"\n" +
	"Definition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05range\x18\x03 \x03(\x05R\x05range\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\x12\x18\n" +
	"\acontent\x18\x05 \x01(\fR\acontentB2Z0internal/store/codegraph/codegraphpb;codegraphpbb\x06proto3"

var (
	file_internal_store_codegraph_definition_proto_rawDescOnce sync.Once
	file_internal_store_codegraph_definition_proto_rawDescData []byte
)

func file_internal_store_codegraph_definition_proto_rawDescGZIP() []byte {
	file_internal_store_codegraph_definition_proto_rawDescOnce.Do(func() {
		file_internal_store_codegraph_definition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_store_codegraph_definition_proto_rawDesc), len(file_internal_store_codegraph_definition_proto_rawDesc)))
	})
	return file_internal_store_codegraph_definition_proto_rawDescData
}

var file_internal_store_codegraph_definition_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_store_codegraph_definition_proto_goTypes = []any{
	(*CodeDefinition)(nil), // 0: codegraphpb.CodeDefinition
	(*Definition)(nil),     // 1: codegraphpb.Definition
}
var file_internal_store_codegraph_definition_proto_depIdxs = []int32{
	1, // 0: codegraphpb.CodeDefinition.definitions:type_name -> codegraphpb.Definition
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_store_codegraph_definition_proto_init() }
func file_internal_store_codegraph_definition_proto_init() {
	if File_internal_store_codegraph_definition_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_store_codegraph_definition_proto_rawDesc), len(file_internal_store_codegraph_definition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_store_codegraph_definition_proto_goTypes,
		DependencyIndexes: file_internal_store_codegraph_definition_proto_depIdxs,
		MessageInfos:      file_internal_store_codegraph_definition_proto_msgTypes,
	}.Build()
	File_internal_store_codegraph_definition_proto = out.File
	file_internal_store_codegraph_definition_proto_goTypes = nil
	file_internal_store_codegraph_definition_proto_depIdxs = nil
}
