// go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
// protoc --go_out=. internal/store/codegraph/document.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: internal/store/codegraph/document.proto

package codegraphpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RelationType 定义关系类型
type RelationType int32

const (
	RelationType_RELATION_TYPE_UNKNOWN    RelationType = 0 // Protobuf enum must start with 0
	RelationType_RELATION_DEFINITION      RelationType = 1
	RelationType_RELATION_TYPE_DEFINITION RelationType = 2
	RelationType_RELATION_IMPLEMENTATION  RelationType = 3
	RelationType_RELATION_REFERENCE       RelationType = 4
)

// Enum value maps for RelationType.
var (
	RelationType_name = map[int32]string{
		0: "RELATION_TYPE_UNKNOWN",
		1: "RELATION_DEFINITION",
		2: "RELATION_TYPE_DEFINITION",
		3: "RELATION_IMPLEMENTATION",
		4: "RELATION_REFERENCE",
	}
	RelationType_value = map[string]int32{
		"RELATION_TYPE_UNKNOWN":    0,
		"RELATION_DEFINITION":      1,
		"RELATION_TYPE_DEFINITION": 2,
		"RELATION_IMPLEMENTATION":  3,
		"RELATION_REFERENCE":       4,
	}
)

func (x RelationType) Enum() *RelationType {
	p := new(RelationType)
	*p = x
	return p
}

func (x RelationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelationType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_store_codegraph_document_proto_enumTypes[0].Descriptor()
}

func (RelationType) Type() protoreflect.EnumType {
	return &file_internal_store_codegraph_document_proto_enumTypes[0]
}

func (x RelationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelationType.Descriptor instead.
func (RelationType) EnumDescriptor() ([]byte, []int) {
	return file_internal_store_codegraph_document_proto_rawDescGZIP(), []int{0}
}

// Relation 表示符号在文件中的出现位置（作为关系的终点）
type Relation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                // 符号名 (符号的唯一标识符，例如 SCIP 符号描述符)
	FilePath      string                 `protobuf:"bytes,2,opt,name=filePath,proto3" json:"filePath,omitempty"`                                        // 文件路径
	Range         []int32                `protobuf:"varint,3,rep,packed,name=range,proto3" json:"range,omitempty"`                                      // 范围信息 [startLine,startCol,endLine,endCol]
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                                          // 符号内容（代码片段）
	RelationType  RelationType           `protobuf:"varint,5,opt,name=relationType,proto3,enum=codegraphpb.RelationType" json:"relationType,omitempty"` // 节点角色 (表示关系的类型，比如这个 Relation 指向的是一个定义、引用等)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relation) Reset() {
	*x = Relation{}
	mi := &file_internal_store_codegraph_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relation) ProtoMessage() {}

func (x *Relation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_store_codegraph_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relation.ProtoReflect.Descriptor instead.
func (*Relation) Descriptor() ([]byte, []int) {
	return file_internal_store_codegraph_document_proto_rawDescGZIP(), []int{0}
}

func (x *Relation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Relation) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Relation) GetRange() []int32 {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *Relation) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Relation) GetRelationType() RelationType {
	if x != nil {
		return x.RelationType
	}
	return RelationType_RELATION_TYPE_UNKNOWN
}

// Symbol 表示代码库中的一个符号出现（作为图谱的节点）
type Symbol struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // 符号名 (符号的唯一标识符，例如 SCIP 符号描述符)
	Path    string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`       // 所在文件的相对路径
	Content string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"` // 符号内容（代码片段）
	// Role 在这里表示这个 Symbol 出现点在该文件中的角色 (比如是定义点、引用点)
	// 假设 types.SymbolRole 可以映射到 Protobuf enum，或者直接使用 RelationType
	// 为了简单和统一，我们在这里复用 RelationType 来表示出现点的角色
	Role          RelationType `protobuf:"varint,4,opt,name=role,proto3,enum=codegraphpb.RelationType" json:"role,omitempty"`
	Range         []int32      `protobuf:"varint,5,rep,packed,name=range,proto3" json:"range,omitempty"` // [startLine, startCol, endLine, endCol] 这个 Symbol 出现点自身的位置
	Relations     []*Relation  `protobuf:"bytes,6,rep,name=relations,proto3" json:"relations,omitempty"` // 与这个 Symbol 出现点相关的其他出现点或符号关系
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Symbol) Reset() {
	*x = Symbol{}
	mi := &file_internal_store_codegraph_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Symbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Symbol) ProtoMessage() {}

func (x *Symbol) ProtoReflect() protoreflect.Message {
	mi := &file_internal_store_codegraph_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Symbol.ProtoReflect.Descriptor instead.
func (*Symbol) Descriptor() ([]byte, []int) {
	return file_internal_store_codegraph_document_proto_rawDescGZIP(), []int{1}
}

func (x *Symbol) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Symbol) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Symbol) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Symbol) GetRole() RelationType {
	if x != nil {
		return x.Role
	}
	return RelationType_RELATION_TYPE_UNKNOWN
}

func (x *Symbol) GetRange() []int32 {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *Symbol) GetRelations() []*Relation {
	if x != nil {
		return x.Relations
	}
	return nil
}

// Document 表示代码库中的一个文件
type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`       // 文件路径
	Symbols       []*Symbol              `protobuf:"bytes,2,rep,name=symbols,proto3" json:"symbols,omitempty"` // 文件中的符号出现列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_internal_store_codegraph_document_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_internal_store_codegraph_document_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_internal_store_codegraph_document_proto_rawDescGZIP(), []int{2}
}

func (x *Document) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Document) GetSymbols() []*Symbol {
	if x != nil {
		return x.Symbols
	}
	return nil
}

var File_internal_store_codegraph_document_proto protoreflect.FileDescriptor

const file_internal_store_codegraph_document_proto_rawDesc = "" +
	"\n" +
	"'internal/store/codegraph/document.proto\x12\vcodegraphpb\"\xa9\x01\n" +
	"\bRelation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bfilePath\x18\x02 \x01(\tR\bfilePath\x12\x14\n" +
	"\x05range\x18\x03 \x03(\x05R\x05range\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12=\n" +
	"\frelationType\x18\x05 \x01(\x0e2\x19.codegraphpb.RelationTypeR\frelationType\"\xc4\x01\n" +
	"\x06Symbol\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12-\n" +
	"\x04role\x18\x04 \x01(\x0e2\x19.codegraphpb.RelationTypeR\x04role\x12\x14\n" +
	"\x05range\x18\x05 \x03(\x05R\x05range\x123\n" +
	"\trelations\x18\x06 \x03(\v2\x15.codegraphpb.RelationR\trelations\"M\n" +
	"\bDocument\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12-\n" +
	"\asymbols\x18\x02 \x03(\v2\x13.codegraphpb.SymbolR\asymbols*\x95\x01\n" +
	"\fRelationType\x12\x19\n" +
	"\x15RELATION_TYPE_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13RELATION_DEFINITION\x10\x01\x12\x1c\n" +
	"\x18RELATION_TYPE_DEFINITION\x10\x02\x12\x1b\n" +
	"\x17RELATION_IMPLEMENTATION\x10\x03\x12\x16\n" +
	"\x12RELATION_REFERENCE\x10\x04B2Z0internal/store/codegraph/codegraphpb;codegraphpbb\x06proto3"

var (
	file_internal_store_codegraph_document_proto_rawDescOnce sync.Once
	file_internal_store_codegraph_document_proto_rawDescData []byte
)

func file_internal_store_codegraph_document_proto_rawDescGZIP() []byte {
	file_internal_store_codegraph_document_proto_rawDescOnce.Do(func() {
		file_internal_store_codegraph_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_store_codegraph_document_proto_rawDesc), len(file_internal_store_codegraph_document_proto_rawDesc)))
	})
	return file_internal_store_codegraph_document_proto_rawDescData
}

var file_internal_store_codegraph_document_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_store_codegraph_document_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_store_codegraph_document_proto_goTypes = []any{
	(RelationType)(0), // 0: codegraphpb.RelationType
	(*Relation)(nil),  // 1: codegraphpb.Relation
	(*Symbol)(nil),    // 2: codegraphpb.Symbol
	(*Document)(nil),  // 3: codegraphpb.Document
}
var file_internal_store_codegraph_document_proto_depIdxs = []int32{
	0, // 0: codegraphpb.Relation.relationType:type_name -> codegraphpb.RelationType
	0, // 1: codegraphpb.Symbol.role:type_name -> codegraphpb.RelationType
	1, // 2: codegraphpb.Symbol.relations:type_name -> codegraphpb.Relation
	2, // 3: codegraphpb.Document.symbols:type_name -> codegraphpb.Symbol
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_store_codegraph_document_proto_init() }
func file_internal_store_codegraph_document_proto_init() {
	if File_internal_store_codegraph_document_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_store_codegraph_document_proto_rawDesc), len(file_internal_store_codegraph_document_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_store_codegraph_document_proto_goTypes,
		DependencyIndexes: file_internal_store_codegraph_document_proto_depIdxs,
		EnumInfos:         file_internal_store_codegraph_document_proto_enumTypes,
		MessageInfos:      file_internal_store_codegraph_document_proto_msgTypes,
	}.Build()
	File_internal_store_codegraph_document_proto = out.File
	file_internal_store_codegraph_document_proto_goTypes = nil
	file_internal_store_codegraph_document_proto_depIdxs = nil
}
