// go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
// protoc --go_out=. internal/store/codegraph/keys.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: internal/store/codegraph/keys.proto

package codegraphpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// key集合
type KeySet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*KeyRange            `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"` // key列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeySet) Reset() {
	*x = KeySet{}
	mi := &file_internal_store_codegraph_keys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeySet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeySet) ProtoMessage() {}

func (x *KeySet) ProtoReflect() protoreflect.Message {
	mi := &file_internal_store_codegraph_keys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeySet.ProtoReflect.Descriptor instead.
func (*KeySet) Descriptor() ([]byte, []int) {
	return file_internal_store_codegraph_keys_proto_rawDescGZIP(), []int{0}
}

func (x *KeySet) GetKeys() []*KeyRange {
	if x != nil {
		return x.Keys
	}
	return nil
}

type KeyRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocKey        []byte                 `protobuf:"bytes,1,opt,name=docKey,proto3" json:"docKey,omitempty"`
	Range         []int32                `protobuf:"varint,2,rep,packed,name=range,proto3" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRange) Reset() {
	*x = KeyRange{}
	mi := &file_internal_store_codegraph_keys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRange) ProtoMessage() {}

func (x *KeyRange) ProtoReflect() protoreflect.Message {
	mi := &file_internal_store_codegraph_keys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRange.ProtoReflect.Descriptor instead.
func (*KeyRange) Descriptor() ([]byte, []int) {
	return file_internal_store_codegraph_keys_proto_rawDescGZIP(), []int{1}
}

func (x *KeyRange) GetDocKey() []byte {
	if x != nil {
		return x.DocKey
	}
	return nil
}

func (x *KeyRange) GetRange() []int32 {
	if x != nil {
		return x.Range
	}
	return nil
}

var File_internal_store_codegraph_keys_proto protoreflect.FileDescriptor

const file_internal_store_codegraph_keys_proto_rawDesc = "" +
	"\n" +
	"#internal/store/codegraph/keys.proto\x12\vcodegraphpb\"3\n" +
	"\x06KeySet\x12)\n" +
	"\x04keys\x18\x01 \x03(\v2\x15.codegraphpb.KeyRangeR\x04keys\"8\n" +
	"\bKeyRange\x12\x16\n" +
	"\x06docKey\x18\x01 \x01(\fR\x06docKey\x12\x14\n" +
	"\x05range\x18\x02 \x03(\x05R\x05rangeB2Z0internal/store/codegraph/codegraphpb;codegraphpbb\x06proto3"

var (
	file_internal_store_codegraph_keys_proto_rawDescOnce sync.Once
	file_internal_store_codegraph_keys_proto_rawDescData []byte
)

func file_internal_store_codegraph_keys_proto_rawDescGZIP() []byte {
	file_internal_store_codegraph_keys_proto_rawDescOnce.Do(func() {
		file_internal_store_codegraph_keys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_store_codegraph_keys_proto_rawDesc), len(file_internal_store_codegraph_keys_proto_rawDesc)))
	})
	return file_internal_store_codegraph_keys_proto_rawDescData
}

var file_internal_store_codegraph_keys_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_store_codegraph_keys_proto_goTypes = []any{
	(*KeySet)(nil),   // 0: codegraphpb.KeySet
	(*KeyRange)(nil), // 1: codegraphpb.KeyRange
}
var file_internal_store_codegraph_keys_proto_depIdxs = []int32{
	1, // 0: codegraphpb.KeySet.keys:type_name -> codegraphpb.KeyRange
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_store_codegraph_keys_proto_init() }
func file_internal_store_codegraph_keys_proto_init() {
	if File_internal_store_codegraph_keys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_store_codegraph_keys_proto_rawDesc), len(file_internal_store_codegraph_keys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_store_codegraph_keys_proto_goTypes,
		DependencyIndexes: file_internal_store_codegraph_keys_proto_depIdxs,
		MessageInfos:      file_internal_store_codegraph_keys_proto_msgTypes,
	}.Build()
	File_internal_store_codegraph_keys_proto = out.File
	file_internal_store_codegraph_keys_proto_goTypes = nil
	file_internal_store_codegraph_keys_proto_depIdxs = nil
}
